blog/urls.py
# blog/urls.py
from django.conf.urls import url, include

from blog import views_cbv
from django.conf.urls.static import static

from . import views
from django.urls import path
from blog import views
from django.conf import settings

app_name='blog'
urlpatterns = [
    url(r'^$', views_cbv.post_list, name='post_list'),
    url(r'^new/$', views.post_new, name='post_new'),
    path('cbv/new/', views_cbv.post_new),
    url(r'^detail/(?P<pk>\d+)/$', views_cbv.post_detail, name='post_detail'),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete, name='post_delete'),
    #url(r'^(?P<id>\d+)/comments/$', views.comment_list, name='comment_list'),
    #url(r'^(?P<post_id>\d+)/comments/(?P<id>\d+)/edit/$', views.comment_edit, name='comment_edit'),
    #url(r'^(?P<post_id>\d+)/comments/(?P<id>\d+)/delete/$', views.comment_delete, name='comment_delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

first_django/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, re_path
from django.conf.urls import include, url
def root(request):
    return redirect('blog:post_list')

urlpatterns = [
    path('', lambda r: redirect('blog:post_list'), name='root'),
    path('admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    path('accounts/', include('accounts.urls')),
    url(r'^shop/', include('shop.urls', namespace='shop'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blog/models.py
from django.db import models
import re
from django.contrib.auth.models import User
from django.forms import ValidationError
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.
from django.urls import reverse


def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid  Lng/Lat Type')

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )

    #author = models.CharField(max_length=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, verbose_name="Article Headline", help_text="Write the title shorter than 100 letters/whitespaces.")
    content = models.TextField(verbose_name="Article Content")
    photo = ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d',
                                     processors=[Thumbnail(300,300)],
                                     format='JPEG',
                                     options={'quality': 60})
    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50, blank=True, validators=[lnglat_validator], help_text='Write in the format of longitude and latitude.')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    tag_set = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name

blog/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from .models import Post
from .Forms import PostForm

# Create your views here.
def post_list(request):
    qs= Post.objects.all()
    q = request.GET.get('q','')
    if q:
        qs = qs.filter(title__icontains=q)
    # messages.error(request, 'error message test')
    return render(request, 'blog/post_list.html', {
        'post_list': qs,
        'q':q,
    })

def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    return render(request, 'blog/post_detail.html',{
        'post': post,
    })


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, 'saved the new post')
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form':form,
    })

def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, 'edited the post')
            return redirect(post)
        pass
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form':form,
    })

blog/templates/blog/layout.html
{% extends "layout.html" %}
{% block title %}askdjango's blog{% endblock %}

blog/templates/blog/post_confirm_delete.html
<h1>confirm deleting: {{ post }}</h1>
Are you sure you want to delete the post?
<form action="" method="post">
    {% csrf_token %}
    <a href="{{ post.get_absolute_url }}">Nope, cancel. </a>
    <input type="submit" value="Yes, go on." />
</form>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load imagekit %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ post.title }}</h2>
            {# <img src="/media/{{ post.photo }}" style="max-width: 100%;" /> #}
            {% if post.photo %}
                <img src="{{ post.photo.url }}" style="max-width: 100%" />
                {% thumbnail "100x100" post.photo %}
                {% thumbnail "100x100" post.photo as thumb %}
                <img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" />
                {% thumbnail "100x100" post.photo -- style="" onclick="" class="" %}
            {% endif %}
            {{ post.content|linebreaks }}
            <hr/>
            <h3>COMMENTS</h3>
            <ul>
                {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.message }}
                        <small>by {{ comment.author }}</small>
                        <small>at {{ comment.updated_at }}</small>
                    </li>
                {% endfor %}
            </ul>
            <hr>
            <a href="{% url "blog:post_list" %}" class="btn btn-primary">post list</a>
            <a href="{% url "blog:post_edit" post.id %}" class="btn btn-default">edit post</a>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {%  csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Django Template <sup>by AskDjango</sup></h1>
        <p>this is a django tutorial</p>
        <p>
            <a class="btn btn-lg btn-primary" href="http://facebook.com/groups/askdjango">
                AskDjango FB Group &raquo;
            </a>
        </p>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-info">
                <ul>
                    <li>Try accessing to http://127.0.0.1:8000/blog</li>
                    <li>Reason why the template path is set as blog/templates/blog/post_list.html<br/>
                        instead of blog/templates/post_list.html will be explained later.</li>
                </ul>
            </div>
            <a href="{% url "blog:post_new" %}" class="btn btn-primary pull-right">New Post</a>

            <form action="" method="get">
                <input type="text" name="q" value="{{ q }}" />
                <input type="submit" value="검색" class="btn btn-primary"/>
            </form>
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                        <th>author</th>
                        <th>updated_at</th>
                    </tr>
                </thead>
                <tbody>
                {% for post in post_list %}
                    <tr>
                        <td>{{ post.id }}</td>
                        <td><a href="{% url "blog:post_detail" post.id %}">
                            {{ post.title }}
                        </a></td>
                        <td><small>by {{ post.author }}</small></td>
                        <td><small>at {{ post.updated_at }}</small></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}